### ISSUE TITLE
TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by maxcc0** [LouisBrunner/react-dnd-multi-backend#8]
I get this error on the require statement:

```
TypeError: Super expression must either be null or a function, not undefined
    at _inherits (C:\Apps\workspace\betty.acdb.ui\node_modules\react-dnd-multi-backend\lib\Preview.js:26:113)
    at C:\Apps\workspace\betty.acdb.ui\node_modules\react-dnd-multi-backend\lib\Preview.js:33:3
    at Object.<anonymous> (C:\Apps\workspace\betty.acdb.ui\node_modules\react-dnd-multi-backend\lib\Preview.js:58:2)
    at Module._compile (module.js:435:26)
```

**Comment by LouisBrunner** [comment]
Hi @maxcc0,

Could you give me a bit more context about how you got this error? For example your usage of `Preview`, etc.

Thanks,

**Comment by LouisBrunner** [comment]
With the recent changes (notably #12), this may be fixed. If it isn't, please add more information on your browser, usage, example code, etc. Thanks!
